### ISSUE TITLE
Error when running server.js

### ISSUE THREAD

**Issue by southchurchbob** [KevinVR/milights-bridge#1]
Hi there,
I'm following the instructions, I think, fully, but when I issue the command "sudo node server.js" I get the following output, all the build to this point appears successful.

"
Setting up EJS...
Initialising Milight bridge connection (version v6)
Checking for updates...

/home/pi/milights-bridge/server.js:477
		.execSync('git rev-parse HEAD')
		 ^
TypeError: Object #<Object> has no method 'execSync'
    at getLastCommitId (/home/pi/milights-bridge/server.js:477:4)
    at refreshUpdateCache (/home/pi/milights-bridge/server.js:492:14)
    at initIBox (/home/pi/milights-bridge/server.js:312:2)
    at Server.<anonymous> (/home/pi/milights-bridge/server.js:290:2)
    at Server.g (events.js:180:16)
    at Server.emit (events.js:92:17)
    at net.js:1055:10
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
"

**Comment by KevinVR** [comment]
Hi!

I must have forgotten to add a package to the package.json.

Running the following command inside the `/milights-bridge/` folder should solve the problem temporarily (until next commit):

`sudo npm install child_process`

 Let me know if you have any other problems!

**Comment by mpartoglou** [comment]
Hi KevinVR,

I noticed the same issue when trying to use the code - I am also running this on the RaspberryPi (which has OSMC as the default build) and am getting the same error as the other user.

I ran both version of the install child_process (as recommended above) - see below for output of both attempts.

Attempt 1: after running sudo npm install child_process
osmc@osmc:~/milights-bridge$ sudo nodejs server.js
Setting up EJS...
Initialising Milight bridge connection (version v6)
Checking for updates...

/home/osmc/milights-bridge/server.js:477
                .execSync('git rev-parse HEAD')
                 ^
TypeError: Object #<Object> has no method 'execSync'
    at getLastCommitId (/home/osmc/milights-bridge/server.js:477:4)
    at refreshUpdateCache (/home/osmc/milights-bridge/server.js:492:14)
    at initIBox (/home/osmc/milights-bridge/server.js:312:2)
    at Server.<anonymous> (/home/osmc/milights-bridge/server.js:290:2)
    at Server.g (events.js:180:16)
    at Server.emit (events.js:92:17)
    at net.js:1055:10
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3


Attempt 2
osmc@osmc:~/milights-bridge$ sudo npm install -g child_process
child_process@1.0.2 /usr/local/lib/node_modules/child_process
osmc@osmc:~/milights-bridge$ sudo nodejs server.js
Setting up EJS...
Initialising Milight bridge connection (version v6)
Checking for updates...

/home/osmc/milights-bridge/server.js:477
                .execSync('git rev-parse HEAD')
                 ^
TypeError: Object #<Object> has no method 'execSync'
    at getLastCommitId (/home/osmc/milights-bridge/server.js:477:4)
    at refreshUpdateCache (/home/osmc/milights-bridge/server.js:492:14)
    at initIBox (/home/osmc/milights-bridge/server.js:312:2)
    at Server.<anonymous> (/home/osmc/milights-bridge/server.js:290:2)
    at Server.g (events.js:180:16)
    at Server.emit (events.js:92:17)
    at net.js:1055:10
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
osmc@osmc:~/milights-bridge$

Hope this helps with your debugging, happy to test again on the next commit.

**Comment by Lucas183** [comment]
Hi KevinVR,

thank you for the great work! Unfortunately, I've got the same issue. Is there any other solution than running the 2 commands? It didn't work for me :( .

**Comment by KevinVR** [comment]
I will take a look at it!

**Comment by KevinVR** [comment]
@mpartoglou  @Lucas183 @southchurchbob 
Sorry for the delay, please make a fresh install, I have updated some things that should solve these problems :).

Let me know if it works!

**Comment by Lucas183** [comment]
![image](https://user-images.githubusercontent.com/30804122/29211481-9886079c-7e99-11e7-9c3e-b43a764a6177.png)
Now it's a different error message. But still doesn't work for me :(

**Comment by mwittig** [comment]
I think the the problem is that you "child_process" included as an dependency in package.json which is jsut a "security holding package on npmjs". My suggestion is that to remove that. As "child_process" is an API of the Node.JS base library there is no for an dependency entry for that.

**Comment by KevinVR** [comment]
@mwittig Thanks for the advice. 

@Lucas183 I forgot to fix the same error in another part of the code, try again please :). It is possible that the update system (latest version) might not work, but this is a temporary fix. I'll use syncexec (like they did here https://github.com/lerna/lerna/commit/062ae97ea8b33be825670baa43c76f422fd603e6 to solve the same problem) in the future to solve it, if it works like this.

**Comment by Lucas183** [comment]
Hi all,

sorry, I was on vacation, so I wasn't able to test it until now.
The issue above seems to be solved, now I get a different one, probably because I did not set it up correcttly, maybe you can help me here.

![img_20170825_154729](https://user-images.githubusercontent.com/30804122/29716772-ef6c508e-89ac-11e7-96b8-e5a774d7d4b4.jpg)
